#!/usr/bin/env python3
"""Regenerates web/src/app/xtce-reference.ts from the XTCE 1.2 XSD's own
<documentation> blocks. Run from the repo root:

    python3 tools/extract-reference-docs.py

Keeps the in-app reference sheet mechanically tied to the spec text rather
than hand-written summaries that drift.
"""
import re
import xml.etree.ElementTree as ET

XS = "{http://www.w3.org/2001/XMLSchema}"
XSD_PATH = "reference/1.2/SpaceSystem.xsd"
OUT_PATH = "web/src/app/xtce-reference.ts"

# UI construct key -> XSD complexType whose documentation describes it.
CONSTRUCTS = {
    "SpaceSystem": "SpaceSystemType",
    "Parameter": "ParameterType",
    "SequenceContainer": "SequenceContainerType",
    "Message": "MessageType",
    "MetaCommand": "MetaCommandType",
    "BlockMetaCommand": "BlockMetaCommandType",
    "IntegerParameterType": "IntegerParameterType",
    "FloatParameterType": "FloatParameterType",
    "StringParameterType": "StringParameterType",
    "BooleanParameterType": "BooleanParameterType",
    "EnumeratedParameterType": "EnumeratedParameterType",
    "BinaryParameterType": "BinaryParameterType",
    "RelativeTimeParameterType": "RelativeTimeParameterType",
    "AbsoluteTimeParameterType": "AbsoluteTimeParameterType",
    "ArrayParameterType": "ArrayParameterType",
    "AggregateParameterType": "AggregateParameterType",
    "IntegerArgumentType": "IntegerArgumentType",
    "FloatArgumentType": "FloatArgumentType",
    "StringArgumentType": "StringArgumentType",
    "BooleanArgumentType": "BooleanArgumentType",
    "EnumeratedArgumentType": "EnumeratedArgumentType",
    "BinaryArgumentType": "BinaryArgumentType",
    "RelativeTimeArgumentType": "RelativeTimeArgumentType",
    "AbsoluteTimeArgumentType": "AbsoluteTimeArgumentType",
    "ArrayArgumentType": "ArrayArgumentType",
    "AggregateArgumentType": "AggregateArgumentType",
    "CustomAlgorithm": "InputOutputTriggerAlgorithmType",
    "MathAlgorithm": "MathAlgorithmType",
}


def first_documentation(type_element):
    annotation = type_element.find(f"{XS}annotation")
    if annotation is None:
        return None
    documentation = annotation.find(f"{XS}documentation")
    if documentation is None or documentation.text is None:
        return None
    return re.sub(r"\s+", " ", documentation.text).strip()


def main():
    root = ET.parse(XSD_PATH).getroot()
    types = {t.get("name"): t for t in root.findall(f"{XS}complexType")}

    entries = []
    for key, type_name in CONSTRUCTS.items():
        type_element = types.get(type_name)
        text = first_documentation(type_element) if type_element is not None else None
        if text is None:
            # MessageType has no annotation of its own; fall back gracefully.
            text = f"(No documentation block on {type_name} in the XSD.)"
        escaped = text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        entries.append(f"  {key}: {{ source: '{type_name}', text: `{escaped}` }},")

    body = "\n".join(entries)
    output = f"""// GENERATED by tools/extract-reference-docs.py from {XSD_PATH} — do not edit by
// hand; rerun the script to refresh. The text is the XSD's own <documentation>.

export interface ReferenceEntry {{
  source: string;
  text: string;
}}

export const XTCE_REFERENCE: Record<string, ReferenceEntry> = {{
{body}
}};
"""
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"wrote {OUT_PATH} with {len(entries)} entries")


if __name__ == "__main__":
    main()
